# Generated by Django 4.1.7 on 2023-03-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512, unique=True)),
                ("short_name", models.CharField(max_length=512, unique=True)),
                ("code", models.CharField(max_length=64, unique=True)),
            ],
        ),
    ]
