# Generated by Django 4.1.7 on 2023-03-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_edition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edition",
            name="page_count",
            field=models.IntegerField(default=0),
        ),
    ]
